// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module atan2_cordic_double_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        y_in,
        x_in,
        ap_return
);

parameter    ap_ST_fsm_state1 = 16'd1;
parameter    ap_ST_fsm_state2 = 16'd2;
parameter    ap_ST_fsm_state3 = 16'd4;
parameter    ap_ST_fsm_state4 = 16'd8;
parameter    ap_ST_fsm_state5 = 16'd16;
parameter    ap_ST_fsm_state6 = 16'd32;
parameter    ap_ST_fsm_state7 = 16'd64;
parameter    ap_ST_fsm_state8 = 16'd128;
parameter    ap_ST_fsm_state9 = 16'd256;
parameter    ap_ST_fsm_state10 = 16'd512;
parameter    ap_ST_fsm_state11 = 16'd1024;
parameter    ap_ST_fsm_state12 = 16'd2048;
parameter    ap_ST_fsm_state13 = 16'd4096;
parameter    ap_ST_fsm_state14 = 16'd8192;
parameter    ap_ST_fsm_state15 = 16'd16384;
parameter    ap_ST_fsm_state16 = 16'd32768;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [63:0] y_in;
input  [63:0] x_in;
output  [63:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[63:0] ap_return;

(* fsm_encoding = "none" *) reg   [15:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [63:0] grp_atan2_generic_fu_163_ap_return;
reg   [63:0] reg_182;
wire    ap_CS_fsm_state3;
wire    grp_atan2_generic_fu_163_ap_ready;
wire    grp_atan2_generic_fu_163_ap_done;
wire    ap_CS_fsm_state4;
wire   [0:0] and_ln757_fu_252_p2;
reg   [0:0] and_ln757_reg_515;
wire   [0:0] and_ln757_1_fu_270_p2;
reg   [0:0] and_ln757_1_reg_519;
wire   [0:0] icmp_ln833_fu_276_p2;
reg   [0:0] icmp_ln833_reg_523;
wire   [0:0] icmp_ln833_5_fu_282_p2;
reg   [0:0] icmp_ln833_5_reg_527;
wire   [0:0] and_ln762_fu_288_p2;
reg   [0:0] and_ln762_reg_532;
wire   [0:0] icmp_ln833_6_fu_294_p2;
reg   [0:0] icmp_ln833_6_reg_536;
wire   [0:0] icmp_ln833_7_fu_300_p2;
reg   [0:0] icmp_ln833_7_reg_540;
wire   [0:0] and_ln766_fu_306_p2;
reg   [0:0] and_ln766_reg_545;
wire   [1:0] tmp_s_fu_312_p3;
reg   [1:0] tmp_s_reg_549;
wire   [0:0] and_ln794_fu_320_p2;
reg   [0:0] and_ln794_reg_553;
wire   [0:0] and_ln794_1_fu_326_p2;
reg   [0:0] and_ln794_1_reg_557;
wire   [63:0] a_fu_344_p1;
reg   [63:0] a_reg_561;
wire   [63:0] b_fu_361_p1;
reg   [63:0] b_reg_568;
wire   [0:0] icmp_ln746_fu_372_p2;
reg   [0:0] icmp_ln746_reg_578;
wire   [0:0] icmp_ln833_8_fu_366_p2;
wire   [0:0] icmp_ln746_1_fu_378_p2;
reg   [0:0] icmp_ln746_1_reg_583;
wire   [63:0] select_ln809_fu_384_p3;
wire   [63:0] bitcast_ln512_5_fu_400_p1;
wire   [63:0] bitcast_ln512_4_fu_412_p1;
wire   [0:0] p_Result_s_fu_192_p3;
wire   [63:0] bitcast_ln512_3_fu_424_p1;
wire   [63:0] bitcast_ln512_2_fu_436_p1;
wire   [63:0] bitcast_ln512_1_fu_448_p1;
wire   [63:0] bitcast_ln512_fu_460_p1;
wire   [63:0] grp_fu_171_p2;
reg   [63:0] tmp_3_i_reg_626;
wire    ap_CS_fsm_state9;
reg   [63:0] d_reg_631;
wire    ap_CS_fsm_state15;
wire   [63:0] bitcast_ln822_1_fu_494_p1;
wire    grp_atan2_generic_fu_163_ap_start;
wire    grp_atan2_generic_fu_163_ap_idle;
reg   [63:0] grp_atan2_generic_fu_163_y_in;
reg   [63:0] grp_atan2_generic_fu_163_x_in;
reg   [63:0] c_reg_82;
wire    ap_CS_fsm_state10;
reg   [63:0] ap_phi_mux_UnifiedRetVal_phi_fu_108_p42;
reg   [63:0] UnifiedRetVal_reg_96;
wire   [63:0] bitcast_ln826_1_fu_507_p1;
wire    ap_CS_fsm_state16;
reg    grp_atan2_generic_fu_163_ap_start_reg;
wire    ap_CS_fsm_state2;
wire   [0:0] and_ln746_1_fu_478_p2;
reg   [63:0] grp_fu_171_p0;
reg   [63:0] grp_fu_171_p1;
wire    ap_CS_fsm_state5;
wire    ap_CS_fsm_state11;
wire   [63:0] grp_fu_178_p0;
wire   [63:0] grp_fu_178_p1;
wire   [63:0] p_Val2_s_fu_188_p1;
wire   [63:0] p_Val2_86_fu_214_p1;
wire   [10:0] tmp_V_29_fu_226_p4;
wire   [51:0] tmp_V_30_fu_236_p1;
wire   [0:0] icmp_ln833_3_fu_240_p2;
wire   [0:0] icmp_ln837_fu_246_p2;
wire   [10:0] tmp_V_fu_200_p4;
wire   [51:0] tmp_V_28_fu_210_p1;
wire   [0:0] icmp_ln833_4_fu_258_p2;
wire   [0:0] icmp_ln837_1_fu_264_p2;
wire   [0:0] p_Result_64_fu_218_p3;
wire   [62:0] trunc_ln368_fu_332_p1;
wire   [63:0] p_Result_71_fu_336_p3;
wire   [62:0] trunc_ln368_1_fu_349_p1;
wire   [63:0] p_Result_72_fu_353_p3;
wire   [63:0] p_Result_70_fu_392_p3;
wire   [63:0] p_Result_69_fu_404_p3;
wire   [63:0] p_Result_68_fu_416_p3;
wire   [63:0] p_Result_67_fu_428_p3;
wire   [63:0] p_Result_66_fu_440_p3;
wire   [63:0] p_Result_65_fu_452_p3;
wire   [0:0] or_ln746_fu_464_p2;
wire   [0:0] or_ln746_1_fu_468_p2;
wire   [0:0] and_ln746_fu_472_p2;
wire   [0:0] grp_fu_178_p2;
wire   [63:0] bitcast_ln822_fu_484_p1;
wire   [63:0] xor_ln822_fu_488_p2;
wire   [63:0] bitcast_ln826_fu_498_p1;
wire   [63:0] xor_ln826_fu_501_p2;
reg   [63:0] ap_return_preg;
reg   [15:0] ap_NS_fsm;
reg    ap_condition_571;

// power-on initialization
initial begin
#0 ap_CS_fsm = 16'd1;
#0 grp_atan2_generic_fu_163_ap_start_reg = 1'b0;
#0 ap_return_preg = 64'd0;
end

atan2_generic grp_atan2_generic_fu_163(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_atan2_generic_fu_163_ap_start),
    .ap_done(grp_atan2_generic_fu_163_ap_done),
    .ap_idle(grp_atan2_generic_fu_163_ap_idle),
    .ap_ready(grp_atan2_generic_fu_163_ap_ready),
    .y_in(grp_atan2_generic_fu_163_y_in),
    .x_in(grp_atan2_generic_fu_163_x_in),
    .ap_return(grp_atan2_generic_fu_163_ap_return)
);

top_level_dsub_64sc4 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
top_level_dsub_64sc4_U39(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_171_p0),
    .din1(grp_fu_171_p1),
    .ce(1'b1),
    .dout(grp_fu_171_p2)
);

top_level_dcmp_64tde #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 1 ))
top_level_dcmp_64tde_U40(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_178_p0),
    .din1(grp_fu_178_p1),
    .ce(1'b1),
    .opcode(5'd2),
    .dout(grp_fu_178_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_preg <= 64'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state16)) begin
            ap_return_preg <= ap_phi_mux_UnifiedRetVal_phi_fu_108_p42;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_atan2_generic_fu_163_ap_start_reg <= 1'b0;
    end else begin
        if ((((1'b1 == ap_CS_fsm_state2) & (1'd1 == and_ln746_1_fu_478_p2)) | ((1'd0 == and_ln746_1_fu_478_p2) & (1'b1 == ap_CS_fsm_state2)))) begin
            grp_atan2_generic_fu_163_ap_start_reg <= 1'b1;
        end else if ((grp_atan2_generic_fu_163_ap_ready == 1'b1)) begin
            grp_atan2_generic_fu_163_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln833_6_fu_294_p2 == 1'd1) & (1'd0 == and_ln766_fu_306_p2) & (1'd0 == and_ln762_fu_288_p2) & (icmp_ln833_fu_276_p2 == 1'd0) & (1'd0 == and_ln757_1_fu_270_p2) & (1'd0 == and_ln757_fu_252_p2) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        UnifiedRetVal_reg_96 <= bitcast_ln512_5_fu_400_p1;
    end else if (((icmp_ln833_fu_276_p2 == 1'd1) & (1'd0 == and_ln766_fu_306_p2) & (1'd0 == and_ln762_fu_288_p2) & (p_Result_s_fu_192_p3 == 1'd0) & (1'd0 == and_ln757_1_fu_270_p2) & (1'd0 == and_ln757_fu_252_p2) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        UnifiedRetVal_reg_96 <= bitcast_ln512_4_fu_412_p1;
    end else if (((icmp_ln833_fu_276_p2 == 1'd1) & (1'd0 == and_ln766_fu_306_p2) & (1'd0 == and_ln762_fu_288_p2) & (1'd0 == and_ln757_1_fu_270_p2) & (1'd0 == and_ln757_fu_252_p2) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (p_Result_s_fu_192_p3 == 1'd1))) begin
        UnifiedRetVal_reg_96 <= bitcast_ln512_3_fu_424_p1;
    end else if (((1'd1 == and_ln766_fu_306_p2) & (1'd0 == and_ln762_fu_288_p2) & (1'd0 == and_ln757_1_fu_270_p2) & (1'd0 == and_ln757_fu_252_p2) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        UnifiedRetVal_reg_96 <= bitcast_ln512_2_fu_436_p1;
    end else if (((1'd1 == and_ln762_fu_288_p2) & (p_Result_s_fu_192_p3 == 1'd0) & (1'd0 == and_ln757_1_fu_270_p2) & (1'd0 == and_ln757_fu_252_p2) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        UnifiedRetVal_reg_96 <= bitcast_ln512_1_fu_448_p1;
    end else if (((1'd1 == and_ln762_fu_288_p2) & (1'd0 == and_ln757_1_fu_270_p2) & (1'd0 == and_ln757_fu_252_p2) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (p_Result_s_fu_192_p3 == 1'd1))) begin
        UnifiedRetVal_reg_96 <= bitcast_ln512_fu_460_p1;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & ((1'd1 == and_ln757_1_fu_270_p2) | (1'd1 == and_ln757_fu_252_p2)))) begin
        UnifiedRetVal_reg_96 <= 64'd9223372036854775807;
    end else if (((1'd1 == and_ln794_1_fu_326_p2) & (1'd0 == and_ln794_fu_320_p2) & (1'd0 == and_ln766_fu_306_p2) & (icmp_ln833_6_fu_294_p2 == 1'd0) & (1'd0 == and_ln762_fu_288_p2) & (icmp_ln833_fu_276_p2 == 1'd0) & (1'd0 == and_ln757_1_fu_270_p2) & (1'd0 == and_ln757_fu_252_p2) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        UnifiedRetVal_reg_96 <= select_ln809_fu_384_p3;
    end else if (((1'd1 == and_ln794_fu_320_p2) & (tmp_s_fu_312_p3 == 2'd0) & (1'd0 == and_ln794_1_fu_326_p2) & (1'd0 == and_ln766_fu_306_p2) & (icmp_ln833_6_fu_294_p2 == 1'd0) & (1'd0 == and_ln762_fu_288_p2) & (icmp_ln833_fu_276_p2 == 1'd0) & (1'd0 == and_ln757_1_fu_270_p2) & (1'd0 == and_ln757_fu_252_p2) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        UnifiedRetVal_reg_96 <= 64'd0;
    end else if (((1'd1 == and_ln794_1_fu_326_p2) & (1'd1 == and_ln794_fu_320_p2) & (tmp_s_fu_312_p3 == 2'd0) & (1'd0 == and_ln766_fu_306_p2) & (icmp_ln833_6_fu_294_p2 == 1'd0) & (1'd0 == and_ln762_fu_288_p2) & (icmp_ln833_fu_276_p2 == 1'd0) & (1'd0 == and_ln757_1_fu_270_p2) & (1'd0 == and_ln757_fu_252_p2) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        UnifiedRetVal_reg_96 <= 64'd4605249457297304856;
    end else if (((tmp_s_reg_549 == 2'd0) & (1'd0 == and_ln794_reg_553) & (1'b1 == ap_CS_fsm_state15))) begin
        UnifiedRetVal_reg_96 <= c_reg_82;
    end else if (((tmp_s_reg_549 == 2'd1) & (1'd0 == and_ln794_reg_553) & (1'b1 == ap_CS_fsm_state15))) begin
        UnifiedRetVal_reg_96 <= bitcast_ln822_1_fu_494_p1;
    end else if (((tmp_s_reg_549 == 2'd2) & (1'd0 == and_ln794_1_reg_557) & (1'd0 == and_ln794_reg_553) & (1'd0 == and_ln766_reg_545) & (icmp_ln833_6_reg_536 == 1'd0) & (1'd0 == and_ln762_reg_532) & (icmp_ln833_reg_523 == 1'd0) & (1'd0 == and_ln757_1_reg_519) & (1'd0 == and_ln757_reg_515) & (1'b1 == ap_CS_fsm_state16))) begin
        UnifiedRetVal_reg_96 <= d_reg_631;
    end else if (((tmp_s_reg_549 == 2'd3) & (1'd0 == and_ln794_1_reg_557) & (1'd0 == and_ln794_reg_553) & (1'd0 == and_ln766_reg_545) & (icmp_ln833_6_reg_536 == 1'd0) & (1'd0 == and_ln762_reg_532) & (icmp_ln833_reg_523 == 1'd0) & (1'd0 == and_ln757_1_reg_519) & (1'd0 == and_ln757_reg_515) & (1'b1 == ap_CS_fsm_state16))) begin
        UnifiedRetVal_reg_96 <= bitcast_ln826_1_fu_507_p1;
    end else if (((1'd1 == and_ln794_fu_320_p2) & (tmp_s_fu_312_p3 == 2'd1) & (1'd0 == and_ln794_1_fu_326_p2) & (1'd0 == and_ln766_fu_306_p2) & (icmp_ln833_6_fu_294_p2 == 1'd0) & (1'd0 == and_ln762_fu_288_p2) & (icmp_ln833_fu_276_p2 == 1'd0) & (1'd0 == and_ln757_1_fu_270_p2) & (1'd0 == and_ln757_fu_252_p2) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        UnifiedRetVal_reg_96 <= 64'd9223372036854775808;
    end else if (((1'd1 == and_ln794_fu_320_p2) & (tmp_s_fu_312_p3 == 2'd2) & (1'd0 == and_ln794_1_fu_326_p2) & (1'd0 == and_ln766_fu_306_p2) & (icmp_ln833_6_fu_294_p2 == 1'd0) & (1'd0 == and_ln762_fu_288_p2) & (icmp_ln833_fu_276_p2 == 1'd0) & (1'd0 == and_ln757_1_fu_270_p2) & (1'd0 == and_ln757_fu_252_p2) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        UnifiedRetVal_reg_96 <= 64'd4614256656552045848;
    end else if (((1'd1 == and_ln794_fu_320_p2) & (tmp_s_fu_312_p3 == 2'd3) & (1'd0 == and_ln794_1_fu_326_p2) & (1'd0 == and_ln766_fu_306_p2) & (icmp_ln833_6_fu_294_p2 == 1'd0) & (1'd0 == and_ln762_fu_288_p2) & (icmp_ln833_fu_276_p2 == 1'd0) & (1'd0 == and_ln757_1_fu_270_p2) & (1'd0 == and_ln757_fu_252_p2) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        UnifiedRetVal_reg_96 <= 64'd13837628693406821656;
    end else if (((1'd1 == and_ln794_1_fu_326_p2) & (1'd1 == and_ln794_fu_320_p2) & (tmp_s_fu_312_p3 == 2'd1) & (1'd0 == and_ln766_fu_306_p2) & (icmp_ln833_6_fu_294_p2 == 1'd0) & (1'd0 == and_ln762_fu_288_p2) & (icmp_ln833_fu_276_p2 == 1'd0) & (1'd0 == and_ln757_1_fu_270_p2) & (1'd0 == and_ln757_fu_252_p2) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        UnifiedRetVal_reg_96 <= 64'd13828621494152080664;
    end else if (((1'd1 == and_ln794_1_fu_326_p2) & (1'd1 == and_ln794_fu_320_p2) & (tmp_s_fu_312_p3 == 2'd2) & (1'd0 == and_ln766_fu_306_p2) & (icmp_ln833_6_fu_294_p2 == 1'd0) & (1'd0 == and_ln762_fu_288_p2) & (icmp_ln833_fu_276_p2 == 1'd0) & (1'd0 == and_ln757_1_fu_270_p2) & (1'd0 == and_ln757_fu_252_p2) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        UnifiedRetVal_reg_96 <= 64'd4612488097114038738;
    end else if (((1'd1 == and_ln794_1_fu_326_p2) & (1'd1 == and_ln794_fu_320_p2) & (tmp_s_fu_312_p3 == 2'd3) & (1'd0 == and_ln766_fu_306_p2) & (icmp_ln833_6_fu_294_p2 == 1'd0) & (1'd0 == and_ln762_fu_288_p2) & (icmp_ln833_fu_276_p2 == 1'd0) & (1'd0 == and_ln757_1_fu_270_p2) & (1'd0 == and_ln757_fu_252_p2) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        UnifiedRetVal_reg_96 <= 64'd13835860133968814546;
    end
end

always @ (posedge ap_clk) begin
    if (((1'd0 == and_ln794_1_fu_326_p2) & (1'd0 == and_ln794_fu_320_p2) & (1'd0 == and_ln766_fu_306_p2) & (icmp_ln833_6_fu_294_p2 == 1'd0) & (1'd0 == and_ln762_fu_288_p2) & (icmp_ln833_fu_276_p2 == 1'd0) & (1'd0 == and_ln757_1_fu_270_p2) & (1'd0 == and_ln757_fu_252_p2) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (icmp_ln833_8_fu_366_p2 == 1'd1))) begin
        c_reg_82 <= 64'd4605249457297304856;
    end else if (((grp_atan2_generic_fu_163_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        c_reg_82 <= grp_atan2_generic_fu_163_ap_return;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        c_reg_82 <= tmp_3_i_reg_626;
    end
end

always @ (posedge ap_clk) begin
    if (((1'd0 == and_ln794_1_fu_326_p2) & (1'd0 == and_ln794_fu_320_p2) & (1'd0 == and_ln766_fu_306_p2) & (icmp_ln833_6_fu_294_p2 == 1'd0) & (1'd0 == and_ln762_fu_288_p2) & (icmp_ln833_fu_276_p2 == 1'd0) & (1'd0 == and_ln757_1_fu_270_p2) & (1'd0 == and_ln757_fu_252_p2) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        a_reg_561[62 : 0] <= a_fu_344_p1[62 : 0];
        b_reg_568[62 : 0] <= b_fu_361_p1[62 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'd0 == and_ln757_fu_252_p2) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        and_ln757_1_reg_519 <= and_ln757_1_fu_270_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        and_ln757_reg_515 <= and_ln757_fu_252_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'd0 == and_ln757_1_fu_270_p2) & (1'd0 == and_ln757_fu_252_p2) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        and_ln762_reg_532 <= and_ln762_fu_288_p2;
        icmp_ln833_5_reg_527 <= icmp_ln833_5_fu_282_p2;
        icmp_ln833_reg_523 <= icmp_ln833_fu_276_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'd0 == and_ln762_fu_288_p2) & (1'd0 == and_ln757_1_fu_270_p2) & (1'd0 == and_ln757_fu_252_p2) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        and_ln766_reg_545 <= and_ln766_fu_306_p2;
        icmp_ln833_6_reg_536 <= icmp_ln833_6_fu_294_p2;
        icmp_ln833_7_reg_540 <= icmp_ln833_7_fu_300_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'd0 == and_ln766_fu_306_p2) & (icmp_ln833_6_fu_294_p2 == 1'd0) & (1'd0 == and_ln762_fu_288_p2) & (icmp_ln833_fu_276_p2 == 1'd0) & (1'd0 == and_ln757_1_fu_270_p2) & (1'd0 == and_ln757_fu_252_p2) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        and_ln794_1_reg_557 <= and_ln794_1_fu_326_p2;
        and_ln794_reg_553 <= and_ln794_fu_320_p2;
        tmp_s_reg_549 <= tmp_s_fu_312_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'd0 == and_ln794_reg_553) & (1'b1 == ap_CS_fsm_state15))) begin
        d_reg_631 <= grp_fu_171_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'd0 == and_ln794_1_fu_326_p2) & (1'd0 == and_ln794_fu_320_p2) & (1'd0 == and_ln766_fu_306_p2) & (icmp_ln833_6_fu_294_p2 == 1'd0) & (1'd0 == and_ln762_fu_288_p2) & (icmp_ln833_fu_276_p2 == 1'd0) & (icmp_ln833_8_fu_366_p2 == 1'd0) & (1'd0 == and_ln757_1_fu_270_p2) & (1'd0 == and_ln757_fu_252_p2) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        icmp_ln746_1_reg_583 <= icmp_ln746_1_fu_378_p2;
        icmp_ln746_reg_578 <= icmp_ln746_fu_372_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((((grp_atan2_generic_fu_163_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4)) | ((grp_atan2_generic_fu_163_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3)))) begin
        reg_182 <= grp_atan2_generic_fu_163_ap_return;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        tmp_3_i_reg_626 <= grp_fu_171_p2;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state16) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_571)) begin
        if ((tmp_s_reg_549 == 2'd2)) begin
            ap_phi_mux_UnifiedRetVal_phi_fu_108_p42 = d_reg_631;
        end else if ((tmp_s_reg_549 == 2'd3)) begin
            ap_phi_mux_UnifiedRetVal_phi_fu_108_p42 = bitcast_ln826_1_fu_507_p1;
        end else begin
            ap_phi_mux_UnifiedRetVal_phi_fu_108_p42 = UnifiedRetVal_reg_96;
        end
    end else begin
        ap_phi_mux_UnifiedRetVal_phi_fu_108_p42 = UnifiedRetVal_reg_96;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        ap_return = ap_phi_mux_UnifiedRetVal_phi_fu_108_p42;
    end else begin
        ap_return = ap_return_preg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_atan2_generic_fu_163_x_in = a_reg_561;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_atan2_generic_fu_163_x_in = b_reg_568;
    end else begin
        grp_atan2_generic_fu_163_x_in = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_atan2_generic_fu_163_y_in = b_reg_568;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_atan2_generic_fu_163_y_in = a_reg_561;
    end else begin
        grp_atan2_generic_fu_163_y_in = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        grp_fu_171_p0 = 64'd4614256656552045848;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        grp_fu_171_p0 = 64'd4609753056924675352;
    end else begin
        grp_fu_171_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        grp_fu_171_p1 = c_reg_82;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        grp_fu_171_p1 = reg_182;
    end else begin
        grp_fu_171_p1 = 'bx;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (~(1'b1 == 1'b1)) begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & ((1'd1 == and_ln757_fu_252_p2) | ((1'd1 == and_ln757_1_fu_270_p2) | ((1'd1 == and_ln762_fu_288_p2) | ((1'd1 == and_ln766_fu_306_p2) | ((icmp_ln833_fu_276_p2 == 1'd1) | ((icmp_ln833_6_fu_294_p2 == 1'd1) | ((1'd1 == and_ln794_1_fu_326_p2) | (1'd1 == and_ln794_fu_320_p2)))))))))) begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end else if (((1'd0 == and_ln794_1_fu_326_p2) & (1'd0 == and_ln794_fu_320_p2) & (1'd0 == and_ln766_fu_306_p2) & (icmp_ln833_6_fu_294_p2 == 1'd0) & (1'd0 == and_ln762_fu_288_p2) & (icmp_ln833_fu_276_p2 == 1'd0) & (1'd0 == and_ln757_1_fu_270_p2) & (1'd0 == and_ln757_fu_252_p2) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (icmp_ln833_8_fu_366_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else if (((1'd0 == and_ln794_1_fu_326_p2) & (1'd0 == and_ln794_fu_320_p2) & (1'd0 == and_ln766_fu_306_p2) & (icmp_ln833_6_fu_294_p2 == 1'd0) & (1'd0 == and_ln762_fu_288_p2) & (icmp_ln833_fu_276_p2 == 1'd0) & (icmp_ln833_8_fu_366_p2 == 1'd0) & (1'd0 == and_ln757_1_fu_270_p2) & (1'd0 == and_ln757_fu_252_p2) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (1'd1 == and_ln746_1_fu_478_p2))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((grp_atan2_generic_fu_163_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((grp_atan2_generic_fu_163_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign a_fu_344_p1 = p_Result_71_fu_336_p3;

assign and_ln746_1_fu_478_p2 = (grp_fu_178_p2 & and_ln746_fu_472_p2);

assign and_ln746_fu_472_p2 = (or_ln746_fu_464_p2 & or_ln746_1_fu_468_p2);

assign and_ln757_1_fu_270_p2 = (icmp_ln837_1_fu_264_p2 & icmp_ln833_4_fu_258_p2);

assign and_ln757_fu_252_p2 = (icmp_ln837_fu_246_p2 & icmp_ln833_3_fu_240_p2);

assign and_ln762_fu_288_p2 = (icmp_ln833_fu_276_p2 & icmp_ln833_5_fu_282_p2);

assign and_ln766_fu_306_p2 = (icmp_ln833_7_fu_300_p2 & icmp_ln833_6_fu_294_p2);

assign and_ln794_1_fu_326_p2 = (icmp_ln833_5_fu_282_p2 & icmp_ln833_3_fu_240_p2);

assign and_ln794_fu_320_p2 = (icmp_ln833_7_fu_300_p2 & icmp_ln833_4_fu_258_p2);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_condition_571 = ((1'd0 == and_ln794_1_reg_557) & (1'd0 == and_ln794_reg_553) & (1'd0 == and_ln766_reg_545) & (icmp_ln833_6_reg_536 == 1'd0) & (1'd0 == and_ln762_reg_532) & (icmp_ln833_reg_523 == 1'd0) & (1'd0 == and_ln757_1_reg_519) & (1'd0 == and_ln757_reg_515) & (1'b1 == ap_CS_fsm_state16));
end

assign b_fu_361_p1 = p_Result_72_fu_353_p3;

assign bitcast_ln512_1_fu_448_p1 = p_Result_66_fu_440_p3;

assign bitcast_ln512_2_fu_436_p1 = p_Result_67_fu_428_p3;

assign bitcast_ln512_3_fu_424_p1 = p_Result_68_fu_416_p3;

assign bitcast_ln512_4_fu_412_p1 = p_Result_69_fu_404_p3;

assign bitcast_ln512_5_fu_400_p1 = p_Result_70_fu_392_p3;

assign bitcast_ln512_fu_460_p1 = p_Result_65_fu_452_p3;

assign bitcast_ln822_1_fu_494_p1 = xor_ln822_fu_488_p2;

assign bitcast_ln822_fu_484_p1 = c_reg_82;

assign bitcast_ln826_1_fu_507_p1 = xor_ln826_fu_501_p2;

assign bitcast_ln826_fu_498_p1 = d_reg_631;

assign grp_atan2_generic_fu_163_ap_start = grp_atan2_generic_fu_163_ap_start_reg;

assign grp_fu_178_p0 = p_Result_71_fu_336_p3;

assign grp_fu_178_p1 = p_Result_72_fu_353_p3;

assign icmp_ln746_1_fu_378_p2 = ((tmp_V_fu_200_p4 != 11'd2047) ? 1'b1 : 1'b0);

assign icmp_ln746_fu_372_p2 = ((tmp_V_29_fu_226_p4 != 11'd2047) ? 1'b1 : 1'b0);

assign icmp_ln833_3_fu_240_p2 = ((tmp_V_29_fu_226_p4 == 11'd2047) ? 1'b1 : 1'b0);

assign icmp_ln833_4_fu_258_p2 = ((tmp_V_fu_200_p4 == 11'd2047) ? 1'b1 : 1'b0);

assign icmp_ln833_5_fu_282_p2 = ((tmp_V_30_fu_236_p1 == 52'd0) ? 1'b1 : 1'b0);

assign icmp_ln833_6_fu_294_p2 = ((tmp_V_fu_200_p4 == 11'd0) ? 1'b1 : 1'b0);

assign icmp_ln833_7_fu_300_p2 = ((tmp_V_28_fu_210_p1 == 52'd0) ? 1'b1 : 1'b0);

assign icmp_ln833_8_fu_366_p2 = ((p_Result_72_fu_353_p3 == p_Result_71_fu_336_p3) ? 1'b1 : 1'b0);

assign icmp_ln833_fu_276_p2 = ((tmp_V_29_fu_226_p4 == 11'd0) ? 1'b1 : 1'b0);

assign icmp_ln837_1_fu_264_p2 = ((tmp_V_28_fu_210_p1 != 52'd0) ? 1'b1 : 1'b0);

assign icmp_ln837_fu_246_p2 = ((tmp_V_30_fu_236_p1 != 52'd0) ? 1'b1 : 1'b0);

assign or_ln746_1_fu_468_p2 = (icmp_ln833_7_reg_540 | icmp_ln746_1_reg_583);

assign or_ln746_fu_464_p2 = (icmp_ln833_5_reg_527 | icmp_ln746_reg_578);

assign p_Result_64_fu_218_p3 = p_Val2_86_fu_214_p1[32'd63];

assign p_Result_65_fu_452_p3 = {{p_Result_64_fu_218_p3}, {63'd4614256656552045848}};

assign p_Result_66_fu_440_p3 = {{p_Result_64_fu_218_p3}, {63'd0}};

assign p_Result_67_fu_428_p3 = {{p_Result_64_fu_218_p3}, {63'd4609753056924675352}};

assign p_Result_68_fu_416_p3 = {{p_Result_64_fu_218_p3}, {63'd4614256656552045848}};

assign p_Result_69_fu_404_p3 = {{p_Result_64_fu_218_p3}, {63'd0}};

assign p_Result_70_fu_392_p3 = {{p_Result_64_fu_218_p3}, {63'd4609753056924675352}};

assign p_Result_71_fu_336_p3 = {{1'd0}, {trunc_ln368_fu_332_p1}};

assign p_Result_72_fu_353_p3 = {{1'd0}, {trunc_ln368_1_fu_349_p1}};

assign p_Result_s_fu_192_p3 = p_Val2_s_fu_188_p1[32'd63];

assign p_Val2_86_fu_214_p1 = y_in;

assign p_Val2_s_fu_188_p1 = x_in;

assign select_ln809_fu_384_p3 = ((p_Result_64_fu_218_p3[0:0] === 1'b1) ? 64'd13833125093779451160 : 64'd4609753056924675352);

assign tmp_V_28_fu_210_p1 = p_Val2_s_fu_188_p1[51:0];

assign tmp_V_29_fu_226_p4 = {{p_Val2_86_fu_214_p1[62:52]}};

assign tmp_V_30_fu_236_p1 = p_Val2_86_fu_214_p1[51:0];

assign tmp_V_fu_200_p4 = {{p_Val2_s_fu_188_p1[62:52]}};

assign tmp_s_fu_312_p3 = {{p_Result_s_fu_192_p3}, {p_Result_64_fu_218_p3}};

assign trunc_ln368_1_fu_349_p1 = p_Val2_s_fu_188_p1[62:0];

assign trunc_ln368_fu_332_p1 = p_Val2_86_fu_214_p1[62:0];

assign xor_ln822_fu_488_p2 = (bitcast_ln822_fu_484_p1 ^ 64'd9223372036854775808);

assign xor_ln826_fu_501_p2 = (bitcast_ln826_fu_498_p1 ^ 64'd9223372036854775808);

always @ (posedge ap_clk) begin
    a_reg_561[63] <= 1'b0;
    b_reg_568[63] <= 1'b0;
end

endmodule //atan2_cordic_double_s
