// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="top_level_wheel,hls_ip_2019_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=1,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7k325t-ffg900-2,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=8.610000,HLS_SYN_LAT=534,HLS_SYN_TPT=none,HLS_SYN_MEM=20,HLS_SYN_DSP=238,HLS_SYN_FF=18356,HLS_SYN_LUT=33602,HLS_VERSION=2019_1}" *)

module top_level_wheel (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        deltaTime,
        torque,
        velocity_x,
        velocity_y,
        load,
        steeringAngle,
        slipRatio,
        slipRatio_ap_vld,
        slipAngle,
        slipAngle_ap_vld,
        force_x,
        force_x_ap_vld,
        force_y,
        force_y_ap_vld,
        angularVel,
        angularVel_ap_vld
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_state2 = 3'd2;
parameter    ap_ST_fsm_state3 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] deltaTime;
input  [31:0] torque;
input  [31:0] velocity_x;
input  [31:0] velocity_y;
input  [31:0] load;
input  [31:0] steeringAngle;
output  [31:0] slipRatio;
output   slipRatio_ap_vld;
output  [31:0] slipAngle;
output   slipAngle_ap_vld;
output  [31:0] force_x;
output   force_x_ap_vld;
output  [31:0] force_y;
output   force_y_ap_vld;
output  [31:0] angularVel;
output   angularVel_ap_vld;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg slipRatio_ap_vld;
reg slipAngle_ap_vld;
reg force_x_ap_vld;
reg force_y_ap_vld;
reg angularVel_ap_vld;

(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [31:0] wheel_angularVelocit;
reg   [31:0] wheel_slipAngle;
reg   [31:0] wheel_slipRatio;
reg   [31:0] wheel_fz;
reg   [31:0] wheel_fx;
wire    grp_update_fu_129_ap_start;
wire    grp_update_fu_129_ap_done;
wire    grp_update_fu_129_ap_idle;
wire    grp_update_fu_129_ap_ready;
wire   [31:0] grp_update_fu_129_wheel_angularVelocit_o;
wire    grp_update_fu_129_wheel_angularVelocit_o_ap_vld;
wire   [31:0] grp_update_fu_129_wheel_slipAngle;
wire    grp_update_fu_129_wheel_slipAngle_ap_vld;
wire   [31:0] grp_update_fu_129_wheel_slipRatio;
wire    grp_update_fu_129_wheel_slipRatio_ap_vld;
wire   [31:0] grp_update_fu_129_wheel_fz;
wire    grp_update_fu_129_wheel_fz_ap_vld;
wire   [31:0] grp_update_fu_129_wheel_fx;
wire    grp_update_fu_129_wheel_fx_ap_vld;
reg    grp_update_fu_129_ap_start_reg;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state3;
reg   [2:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_CS_fsm = 3'd1;
#0 wheel_angularVelocit = 32'd0;
#0 wheel_slipAngle = 32'd0;
#0 wheel_slipRatio = 32'd0;
#0 wheel_fz = 32'd0;
#0 wheel_fx = 32'd0;
#0 grp_update_fu_129_ap_start_reg = 1'b0;
end

update grp_update_fu_129(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_update_fu_129_ap_start),
    .ap_done(grp_update_fu_129_ap_done),
    .ap_idle(grp_update_fu_129_ap_idle),
    .ap_ready(grp_update_fu_129_ap_ready),
    .deltaTime(deltaTime),
    .torque(torque),
    .velocity_x(velocity_x),
    .velocity_z(velocity_y),
    .load(load),
    .steeringAngle(steeringAngle),
    .wheel_angularVelocit_i(wheel_angularVelocit),
    .wheel_angularVelocit_o(grp_update_fu_129_wheel_angularVelocit_o),
    .wheel_angularVelocit_o_ap_vld(grp_update_fu_129_wheel_angularVelocit_o_ap_vld),
    .wheel_slipAngle(grp_update_fu_129_wheel_slipAngle),
    .wheel_slipAngle_ap_vld(grp_update_fu_129_wheel_slipAngle_ap_vld),
    .wheel_slipRatio(grp_update_fu_129_wheel_slipRatio),
    .wheel_slipRatio_ap_vld(grp_update_fu_129_wheel_slipRatio_ap_vld),
    .wheel_fz(grp_update_fu_129_wheel_fz),
    .wheel_fz_ap_vld(grp_update_fu_129_wheel_fz_ap_vld),
    .wheel_fx(grp_update_fu_129_wheel_fx),
    .wheel_fx_ap_vld(grp_update_fu_129_wheel_fx_ap_vld)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_update_fu_129_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_update_fu_129_ap_start_reg <= 1'b1;
        end else if ((grp_update_fu_129_ap_ready == 1'b1)) begin
            grp_update_fu_129_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (grp_update_fu_129_wheel_angularVelocit_o_ap_vld == 1'b1))) begin
        wheel_angularVelocit <= grp_update_fu_129_wheel_angularVelocit_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (grp_update_fu_129_wheel_fx_ap_vld == 1'b1))) begin
        wheel_fx <= grp_update_fu_129_wheel_fx;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (grp_update_fu_129_wheel_fz_ap_vld == 1'b1))) begin
        wheel_fz <= grp_update_fu_129_wheel_fz;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (grp_update_fu_129_wheel_slipAngle_ap_vld == 1'b1))) begin
        wheel_slipAngle <= grp_update_fu_129_wheel_slipAngle;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (grp_update_fu_129_wheel_slipRatio_ap_vld == 1'b1))) begin
        wheel_slipRatio <= grp_update_fu_129_wheel_slipRatio;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        angularVel_ap_vld = 1'b1;
    end else begin
        angularVel_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        force_x_ap_vld = 1'b1;
    end else begin
        force_x_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        force_y_ap_vld = 1'b1;
    end else begin
        force_y_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        slipAngle_ap_vld = 1'b1;
    end else begin
        slipAngle_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        slipRatio_ap_vld = 1'b1;
    end else begin
        slipRatio_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((grp_update_fu_129_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign angularVel = wheel_angularVelocit;

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign force_x = wheel_fx;

assign force_y = wheel_fz;

assign grp_update_fu_129_ap_start = grp_update_fu_129_ap_start_reg;

assign slipAngle = wheel_slipAngle;

assign slipRatio = wheel_slipRatio;

endmodule //top_level_wheel
