// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _top_level_HH_
#define _top_level_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "update.h"

namespace ap_rtl {

struct top_level : public sc_module {
    // Port declarations 18
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_in< sc_lv<32> > deltaTime;
    sc_in< sc_lv<32> > torque;
    sc_in< sc_lv<32> > velocity_x;
    sc_in< sc_lv<32> > velocity_z;
    sc_in< sc_lv<32> > load;
    sc_in< sc_lv<32> > steeringAngle;
    sc_out< sc_lv<32> > force_x;
    sc_out< sc_logic > force_x_ap_vld;
    sc_out< sc_lv<32> > force_z;
    sc_out< sc_logic > force_z_ap_vld;
    sc_out< sc_lv<32> > angularVel;
    sc_out< sc_logic > angularVel_ap_vld;


    // Module declarations
    top_level(sc_module_name name);
    SC_HAS_PROCESS(top_level);

    ~top_level();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    update* grp_update_fu_103;
    sc_signal< sc_lv<2> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_logic > grp_update_fu_103_ap_start;
    sc_signal< sc_logic > grp_update_fu_103_ap_done;
    sc_signal< sc_logic > grp_update_fu_103_ap_idle;
    sc_signal< sc_logic > grp_update_fu_103_ap_ready;
    sc_signal< sc_lv<32> > grp_update_fu_103_ap_return_0;
    sc_signal< sc_lv<32> > grp_update_fu_103_ap_return_1;
    sc_signal< sc_lv<32> > grp_update_fu_103_ap_return_2;
    sc_signal< sc_logic > grp_update_fu_103_ap_start_reg;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_lv<2> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<2> ap_ST_fsm_state1;
    static const sc_lv<2> ap_ST_fsm_state2;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<32> ap_const_lv32_1;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_angularVel();
    void thread_angularVel_ap_vld();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state2();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_force_x();
    void thread_force_x_ap_vld();
    void thread_force_z();
    void thread_force_z_ap_vld();
    void thread_grp_update_fu_103_ap_start();
    void thread_ap_NS_fsm();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
